# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分類名稱')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='父分類')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '商品分類',
                'verbose_name_plural': '商品分類',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='商品名稱')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售價')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本價')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='安全庫存')),
                ('status', models.CharField(choices=[('ACTIVE', '銷售中'), ('INACTIVE', '停售'), ('DISCONTINUED', '已下架')], default='ACTIVE', max_length=15, verbose_name='狀態')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品圖片')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='分類')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='規格名稱')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='規格SKU')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='價格調整')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '商品規格',
                'verbose_name_plural': '商品規格',
                'db_table': 'product_variants',
            },
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='稅別名稱')),
                ('rate', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='稅率 (%)')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '稅別',
                'verbose_name_plural': '稅別',
                'db_table': 'tax_types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.taxtype', verbose_name='稅別'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='單位名稱')),
                ('symbol', models.CharField(max_length=10, verbose_name='符號')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
                'db_table': 'units',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.unit', verbose_name='單位'),
        ),
        migrations.CreateModel(
            name='ProductBarcode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='條碼')),
                ('barcode_type', models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC'), ('CUSTOM', '自訂')], default='EAN13', max_length=10, verbose_name='條碼類型')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主條碼')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='products.productvariant', verbose_name='規格')),
            ],
            options={
                'verbose_name': '商品條碼',
                'verbose_name_plural': '商品條碼',
                'db_table': 'product_barcodes',
                'indexes': [models.Index(fields=['barcode'], name='product_bar_barcode_4f3988_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_sku_fe2039_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
    ]
