# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('po_number', models.CharField(max_length=30, unique=True, verbose_name='採購單號')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已送出'), ('APPROVED', '已核准'), ('PARTIAL', '部分到貨'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=15, verbose_name='狀態')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='總金額')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='預計到貨日')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='送出時間')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_pos', to=settings.AUTH_USER_MODEL, verbose_name='核准者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stores.warehouse', verbose_name='入庫倉庫')),
            ],
            options={
                'verbose_name': '採購單',
                'verbose_name_plural': '採購單',
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=30, unique=True, verbose_name='收貨單號')),
                ('status', models.CharField(choices=[('PENDING', '待驗收'), ('COMPLETED', '已完成')], default='PENDING', max_length=15, verbose_name='狀態')),
                ('receipt_date', models.DateField(verbose_name='收貨日期')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder', verbose_name='採購單')),
            ],
            options={
                'verbose_name': '收貨單',
                'verbose_name_plural': '收貨單',
                'db_table': 'goods_receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已收數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小計')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchaseorder', verbose_name='採購單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '採購單明細',
                'verbose_name_plural': '採購單明細',
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_quantity', models.IntegerField(verbose_name='收貨數量')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.goodsreceipt', verbose_name='收貨單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorderitem', verbose_name='採購單項目')),
            ],
            options={
                'verbose_name': '收貨明細',
                'verbose_name_plural': '收貨明細',
                'db_table': 'goods_receipt_items',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='供應商名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='供應商代碼')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='聯絡人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('payment_terms', models.IntegerField(default=30, verbose_name='付款天數')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '供應商',
                'verbose_name_plural': '供應商',
                'db_table': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier', verbose_name='供應商'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchase_or_po_numb_656941_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchase_or_status_5ac239_idx'),
        ),
    ]
