# Generated by Django 5.2 on 2026-01-08 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('return_number', models.CharField(max_length=30, unique=True, verbose_name='退貨單號')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已送出'), ('APPROVED', '已核准'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=15, verbose_name='狀態')),
                ('reason', models.CharField(choices=[('DEFECTIVE', '瑕疵品'), ('WRONG_ITEM', '品項錯誤'), ('EXCESS', '數量過多'), ('EXPIRED', '過期商品'), ('QUALITY', '品質不良'), ('OTHER', '其他')], default='DEFECTIVE', max_length=20, verbose_name='退貨原因')),
                ('reason_detail', models.TextField(blank=True, verbose_name='原因說明')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='退貨總額')),
                ('return_date', models.DateField(verbose_name='退貨日期')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='核准時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL, verbose_name='核准者')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchasing.purchaseorder', verbose_name='原採購單')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchasing.supplier', verbose_name='供應商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='stores.warehouse', verbose_name='出庫倉庫')),
            ],
            options={
                'verbose_name': '採購退貨單',
                'verbose_name_plural': '採購退貨單',
                'db_table': 'purchase_returns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='退貨數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小計')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='退貨原因')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchasing.purchaseorderitem', verbose_name='原採購項目')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='商品')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchasereturn', verbose_name='退貨單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '採購退貨明細',
                'verbose_name_plural': '採購退貨明細',
                'db_table': 'purchase_return_items',
            },
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('min_quantity', models.IntegerField(default=1, verbose_name='最低訂購量')),
                ('lead_time_days', models.IntegerField(default=7, verbose_name='交期(天)')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='失效日期')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='首選供應商')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='products.product', verbose_name='商品')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='purchasing.supplier', verbose_name='供應商')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '供應商報價',
                'verbose_name_plural': '供應商報價',
                'db_table': 'supplier_prices',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['return_number'], name='purchase_re_return__ae7472_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['status'], name='purchase_re_status_98e5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['supplier', 'product'], name='supplier_pr_supplie_0be68e_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['product', 'is_preferred'], name='supplier_pr_product_4770f2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierprice',
            unique_together={('supplier', 'product', 'effective_from')},
        ),
    ]
