# Generated by Django 5.2 on 2026-01-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='發票號碼')),
                ('invoice_type', models.CharField(choices=[('B2C', '二聯式'), ('B2B', '三聯式'), ('DONATION', '捐贈發票'), ('VOID', '作廢發票')], default='B2C', max_length=10, verbose_name='發票類型')),
                ('status', models.CharField(choices=[('PENDING', '待開立'), ('ISSUED', '已開立'), ('VOIDED', '已作廢'), ('CANCELLED', '已註銷')], default='PENDING', max_length=15, verbose_name='狀態')),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='應稅金額')),
                ('tax_free_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='免稅金額')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='稅額')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='發票總額')),
                ('buyer_tax_id', models.CharField(blank=True, max_length=20, verbose_name='買受人統編')),
                ('buyer_name', models.CharField(blank=True, max_length=100, verbose_name='買受人名稱')),
                ('carrier_type', models.CharField(blank=True, max_length=20, verbose_name='載具類型')),
                ('carrier_id', models.CharField(blank=True, max_length=100, verbose_name='載具號碼')),
                ('donation_code', models.CharField(blank=True, max_length=10, verbose_name='捐贈碼')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='開立時間')),
                ('void_reason', models.TextField(blank=True, verbose_name='作廢原因')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作廢時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='sales.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '發票',
                'verbose_name_plural': '發票',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='品名')),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金額')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice', verbose_name='發票')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '發票明細',
                'verbose_name_plural': '發票明細',
                'db_table': 'invoice_items',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_invoice_7778bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoices_status_07776b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type'], name='invoices_invoice_bcf470_idx'),
        ),
    ]
