# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='等級名稱')),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='折扣率 (%)')),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='點數倍率')),
                ('min_points', models.IntegerField(default=0, verbose_name='升等門檻點數')),
                ('min_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='升等門檻消費金額')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設等級')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '會員等級',
                'verbose_name_plural': '會員等級',
                'db_table': 'customer_levels',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_no', models.CharField(max_length=20, unique=True, verbose_name='會員編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手機號碼')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='電子郵件')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, verbose_name='性別')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('points', models.IntegerField(default=0, verbose_name='累積點數')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累積消費金額')),
                ('total_orders', models.IntegerField(default=0, verbose_name='訂單數')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customerlevel', verbose_name='會員等級')),
            ],
            options={
                'verbose_name': '客戶',
                'verbose_name_plural': '客戶',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(verbose_name='點數異動')),
                ('balance', models.IntegerField(verbose_name='異動後餘額')),
                ('log_type', models.CharField(choices=[('EARN', '獲得'), ('REDEEM', '兌換'), ('ADJUST', '調整'), ('EXPIRE', '過期')], default='EARN', max_length=10, verbose_name='異動類型')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='說明')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='來源類型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='來源ID')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_logs', to='customers.customer', verbose_name='客戶')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '點數異動記錄',
                'verbose_name_plural': '點數異動記錄',
                'db_table': 'points_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['member_no'], name='customers_member__dcbcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customers_phone_91048b_idx'),
        ),
    ]
