# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=50, verbose_name='角色名稱')),
                ('code', models.CharField(choices=[('ADMIN', '系統管理員'), ('MANAGER', '店長/經理'), ('CASHIER', '收銀員'), ('WAREHOUSE', '倉管人員'), ('PURCHASER', '採購人員'), ('VIEWER', '檢視者')], max_length=20, unique=True, verbose_name='角色代碼')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('permissions', models.JSONField(default=dict, help_text='格式: {"module_name": ["read", "write", "delete"]}', verbose_name='權限設定')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主要門店')),
            ],
            options={
                'verbose_name': '使用者門店',
                'verbose_name_plural': '使用者門店',
                'db_table': 'user_stores',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='帳號')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='電子郵件')),
                ('display_name', models.CharField(max_length=100, verbose_name='顯示名稱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手機號碼')),
                ('status', models.CharField(choices=[('ACTIVE', '啟用'), ('INACTIVE', '停用'), ('LOCKED', '鎖定')], default='ACTIVE', max_length=10, verbose_name='狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_staff', models.BooleanField(default=False, verbose_name='員工權限')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最後登入IP')),
                ('login_attempts', models.PositiveIntegerField(default=0, verbose_name='登入嘗試次數')),
                ('password_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='密碼變更時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
