# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='優惠券代碼')),
                ('name', models.CharField(max_length=100, verbose_name='優惠券名稱')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', '百分比折扣'), ('FIXED', '固定金額折扣')], default='PERCENTAGE', max_length=20, verbose_name='折扣類型')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣值')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消費金額')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='最高折扣金額')),
                ('usage_limit', models.IntegerField(default=1, help_text='0表示無限制', verbose_name='使用上限')),
                ('used_count', models.IntegerField(default=0, verbose_name='已使用次數')),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('USED', '已使用'), ('EXPIRED', '已過期'), ('DISABLED', '已停用')], default='ACTIVE', max_length=10, verbose_name='狀態')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '優惠券',
                'verbose_name_plural': '優惠券',
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='折扣金額')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotions.coupon', verbose_name='優惠券')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='sales.order', verbose_name='訂單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '優惠券使用記錄',
                'verbose_name_plural': '優惠券使用記錄',
                'db_table': 'coupon_usages',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='活動名稱')),
                ('description', models.TextField(blank=True, verbose_name='活動說明')),
                ('promotion_type', models.CharField(choices=[('PERCENTAGE', '百分比折扣'), ('FIXED', '固定金額折扣'), ('BUY_X_GET_Y', '買X送Y')], default='PERCENTAGE', max_length=20, verbose_name='促銷類型')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='百分比折扣輸入10代表9折，固定金額直接輸入金額', max_digits=10, verbose_name='折扣值')),
                ('min_purchase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低消費金額')),
                ('buy_quantity', models.IntegerField(default=0, help_text='買X送Y的X', verbose_name='購買數量')),
                ('get_quantity', models.IntegerField(default=0, help_text='買X送Y的Y', verbose_name='贈送數量')),
                ('start_date', models.DateTimeField(verbose_name='開始時間')),
                ('end_date', models.DateTimeField(verbose_name='結束時間')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='products.category', verbose_name='適用分類')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer_levels', models.ManyToManyField(blank=True, related_name='promotions', to='customers.customerlevel', verbose_name='適用會員等級')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='products.product', verbose_name='適用商品')),
                ('stores', models.ManyToManyField(blank=True, related_name='promotions', to='stores.store', verbose_name='適用門店')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '促銷活動',
                'verbose_name_plural': '促銷活動',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='coupons_code_94ae53_idx'),
        ),
    ]
