# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count_number', models.CharField(max_length=30, unique=True, verbose_name='盤點單號')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('IN_PROGRESS', '盤點中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='DRAFT', max_length=15, verbose_name='狀態')),
                ('count_date', models.DateField(verbose_name='盤點日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='stores.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '盤點單',
                'verbose_name_plural': '盤點單',
                'db_table': 'stock_counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('system_quantity', models.IntegerField(verbose_name='系統數量')),
                ('actual_quantity', models.IntegerField(blank=True, null=True, verbose_name='實際數量')),
                ('difference', models.IntegerField(default=0, verbose_name='差異')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount', verbose_name='盤點單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '盤點明細',
                'verbose_name_plural': '盤點明細',
                'db_table': 'stock_count_items',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=30, unique=True, verbose_name='調撥單號')),
                ('status', models.CharField(choices=[('PENDING', '待處理'), ('IN_TRANSIT', '調撥中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', max_length=15, verbose_name='狀態')),
                ('transfer_date', models.DateField(verbose_name='調撥日期')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='stores.warehouse', verbose_name='來源倉庫')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='stores.warehouse', verbose_name='目標倉庫')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '調撥單',
                'verbose_name_plural': '調撥單',
                'db_table': 'stock_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='數量')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer', verbose_name='調撥單')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '調撥明細',
                'verbose_name_plural': '調撥明細',
                'db_table': 'stock_transfer_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='庫存數量')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='可用數量')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='預留數量')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stores.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '庫存',
                'verbose_name_plural': '庫存',
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['warehouse', 'product'], name='inventory_warehou_d4bfbf_idx')],
                'unique_together': {('warehouse', 'product')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('PURCHASE_IN', '採購入庫'), ('SALE_OUT', '銷售出庫'), ('RETURN_IN', '退貨入庫'), ('RETURN_OUT', '退貨出庫'), ('ADJUST_IN', '調整增加'), ('ADJUST_OUT', '調整減少'), ('TRANSFER_IN', '調撥入庫'), ('TRANSFER_OUT', '調撥出庫'), ('COUNT_ADJUST', '盤點調整')], max_length=20, verbose_name='異動類型')),
                ('quantity', models.IntegerField(verbose_name='異動數量')),
                ('balance', models.IntegerField(verbose_name='異動後餘額')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='來源類型')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='來源ID')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='products.product', verbose_name='商品')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stores.warehouse', verbose_name='倉庫')),
            ],
            options={
                'verbose_name': '庫存異動',
                'verbose_name_plural': '庫存異動',
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'product', 'created_at'], name='inventory_m_warehou_84b934_idx')],
            },
        ),
    ]
