# Generated by Django 5.2 on 2026-01-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='門店名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='門店代碼')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('tax_id', models.CharField(blank=True, max_length=20, verbose_name='統一編號')),
                ('status', models.CharField(choices=[('ACTIVE', '營業中'), ('INACTIVE', '停業')], default='ACTIVE', max_length=10, verbose_name='狀態')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='格式: {"mon": "09:00-21:00", ...}', verbose_name='營業時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stores', to=settings.AUTH_USER_MODEL, verbose_name='店長')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '門店',
                'verbose_name_plural': '門店',
                'db_table': 'stores',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='倉庫名稱')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='倉庫代碼')),
                ('warehouse_type', models.CharField(choices=[('STORE', '門店倉庫'), ('WAREHOUSE', '獨立倉庫'), ('VIRTUAL', '虛擬倉庫')], default='STORE', max_length=20, verbose_name='倉庫類型')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='預設倉庫')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='stores.store', verbose_name='所屬門店')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '倉庫',
                'verbose_name_plural': '倉庫',
                'db_table': 'warehouses',
                'ordering': ['store', 'code'],
            },
        ),
    ]
