# Generated by Django 5.2 on 2026-01-08 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='報表名稱')),
                ('report_type', models.CharField(choices=[('SALES', '銷售報表'), ('INVENTORY', '庫存報表'), ('PURCHASE', '採購報表'), ('CUSTOMER', '客戶報表'), ('PRODUCT', '商品報表')], max_length=20, verbose_name='報表類型')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('config', models.JSONField(default=dict, verbose_name='報表設定')),
                ('columns', models.JSONField(default=list, verbose_name='欄位設定')),
                ('filters', models.JSONField(default=dict, verbose_name='篩選條件')),
                ('sort_by', models.CharField(blank=True, max_length=50, verbose_name='排序欄位')),
                ('sort_order', models.CharField(choices=[('ASC', '升冪'), ('DESC', '降冪')], default='DESC', max_length=4, verbose_name='排序方向')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開報表')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '自訂報表',
                'verbose_name_plural': '自訂報表',
                'db_table': 'custom_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='排程名稱')),
                ('report_type', models.CharField(max_length=50, verbose_name='報表類型')),
                ('frequency', models.CharField(choices=[('DAILY', '每日'), ('WEEKLY', '每週'), ('MONTHLY', '每月')], max_length=10, verbose_name='執行頻率')),
                ('run_time', models.TimeField(verbose_name='執行時間')),
                ('run_day', models.IntegerField(blank=True, null=True, verbose_name='執行日(週:1-7/月:1-31)')),
                ('status', models.CharField(choices=[('ACTIVE', '啟用'), ('PAUSED', '暫停'), ('DISABLED', '停用')], default='ACTIVE', max_length=10, verbose_name='狀態')),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF')], default='EXCEL', max_length=10, verbose_name='匯出格式')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次執行時間')),
                ('last_run_status', models.CharField(blank=True, max_length=20, verbose_name='上次執行狀態')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次執行時間')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('custom_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.customreport', verbose_name='自訂報表')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '排程報表',
                'verbose_name_plural': '排程報表',
                'db_table': 'scheduled_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已刪除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='刪除時間')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', '待執行'), ('RUNNING', '執行中'), ('COMPLETED', '已完成'), ('FAILED', '失敗')], default='PENDING', max_length=15, verbose_name='狀態')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='檔案路徑')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('recipients_notified', models.JSONField(default=list, verbose_name='已通知收件人')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='刪除者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.scheduledreport', verbose_name='排程報表')),
            ],
            options={
                'verbose_name': '報表執行紀錄',
                'verbose_name_plural': '報表執行紀錄',
                'db_table': 'report_executions',
                'ordering': ['-created_at'],
            },
        ),
    ]
